name: Pull and build Trendle on push

env:
  NAME: trendle
  SOURCE_REPO: satasatalight/trendle-site
  USERNAME: ${{ github.actor }}
  ADDRESS_SUFFIX: users.noreply.github.com

on: 
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v7
        with:
          path: ./current

      - name: Checkout Source Repo
        uses: actions/checkout@v7
        with:
          repository: ${{ env.SOURCE_REPO }}
          path: ./source

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: 'source'

      - name: Build project
        run: npm run build
        working-directory: 'source'
      
      - name: Delete old build
        run: rm -rf ./current/$NAME
      
      - name: Move new build
        run: mv ./source/dist ./current/$NAME
          
      - name: Commit
        run: |
          git config user.name "$USERNAME"
          git config user.email "$USERNAME@$ADDRESS_SUFFIX"
          git add .
          git commit -m "Pulled and built from $SOURCE_REPO"
        working-directory: 'current'

      - name: Push
        run: git push